import { useAuth } from "@/_core/hooks/useAuth";
import { AccessDenied, WorkspaceHeader } from "@/components/DrivenowShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Check, Loader2, ShieldAlert, X } from "lucide-react";

export default function AdminVerification() {
  const { user, loading, isAuthenticated } = useAuth();
  const queue = trpc.marketplace.admin.verificationQueue.useQuery(undefined, { enabled: Boolean(isAuthenticated && user?.role === "admin") });
  const review = trpc.marketplace.admin.reviewApplication.useMutation({ onSuccess: () => queue.refetch() });
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#141414] text-[10px] font-bold tracking-[0.18em] text-white/55">LOADING ADMIN</div>;
  if (!isAuthenticated || user?.role !== "admin") return <div className="min-h-screen bg-[#e5e6e3]"><AccessDenied title="Admin access required" description="This workspace is limited to the drivenow internal verification team." /></div>;
  return <WorkspaceHeader mode="ADMIN" title="Verification queue"><section className="mt-7 border border-white/20 bg-white/[.04] p-5"><div className="flex items-start justify-between"><div><p className="eyebrow text-white/45">KYC REVIEW</p><p className="mt-2 text-sm text-white/60">Approve verified instructors only after reviewing their submitted profile and document records.</p></div><ShieldAlert className="h-6 w-6 text-[#a6d4b0]" /></div>{queue.isLoading ? <p className="mt-6 text-sm text-white/50">Loading applications…</p> : queue.error ? <p className="mt-6 text-sm text-red-300">{queue.error.message}</p> : <div className="mt-6 space-y-3">{queue.data?.length === 0 ? <p className="border border-dashed border-white/20 p-5 text-sm text-white/50">No instructor applications are waiting for review.</p> : queue.data?.map(({ application, profile, person }) => <article key={application.id} className="border border-white/15 bg-[#141414] p-4"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold tracking-[0.14em] text-[#a6d4b0]">{application.status.replaceAll("_", " ").toUpperCase()}</p><h2 className="mt-1 font-display text-2xl font-bold tracking-[-0.06em]">{person.fullName}</h2><p className="mt-2 text-xs text-white/55">{profile.city} · {profile.serviceAreas} · {profile.transmission} · {profile.hasDualControl ? "Dual control" : "Vehicle declaration pending"}</p></div><div className="text-right text-xs text-white/55"><p>{profile.languages}</p><p className="mt-1">{new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(profile.pricePerLessonPaise / 100)} / lesson</p></div></div><p className="mt-4 border-t border-white/10 pt-3 text-sm leading-6 text-white/65">{profile.bio}</p>{application.status !== "verified" && <div className="mt-4 grid gap-2 sm:grid-cols-3"><Button disabled={review.isPending} className="bg-[#a6d4b0] text-xs font-bold text-[#141414] hover:bg-white" onClick={() => review.mutate({ applicationId: application.id, status: "verified", reviewNotes: "Verified for marketplace listing." })}><Check className="mr-1 h-4 w-4" /> Verify</Button><Button disabled={review.isPending} className="border border-white/25 bg-transparent text-xs font-bold text-white hover:bg-white/10" onClick={() => review.mutate({ applicationId: application.id, status: "needs_more_info", reviewNotes: "Please provide clearer verification documents." })}>Need documents</Button><Button disabled={review.isPending} className="border border-red-300/45 bg-transparent text-xs font-bold text-red-200 hover:bg-red-400/10" onClick={() => review.mutate({ applicationId: application.id, status: "rejected", reviewNotes: "Application requirements were not met." })}><X className="mr-1 h-4 w-4" /> Reject</Button></div>}</article>)}</div>}</section></WorkspaceHeader>;
}
