import { ArrowDownRight, ArrowUpRight, MapPinned, ShieldCheck, WalletCards } from "lucide-react";
import { Link } from "wouter";
import { AppHeader } from "@/components/DrivenowShell";

const pillars = [
  { no: "01", title: "DISCOVER", body: "Start local. Compare verified instructors by vehicle, availability and clear lesson price.", icon: MapPinned },
  { no: "02", title: "BOOK", body: "Choose a package, a time and a pickup point with your full price visible before you pay.", icon: WalletCards },
  { no: "03", title: "LEARN", body: "Track a live booking lifecycle from confirmation through completed lessons and feedback.", icon: ShieldCheck },
];

export default function Home() {
  return <div className="min-h-screen overflow-hidden bg-[#e5e6e3] text-[#141414]"><AppHeader eyebrow="BENGALURU / PILOT" />
    <main>
      <section className="relative border-b border-black/15"><div className="route-grid pointer-events-none absolute inset-0 opacity-70" /><div className="container relative grid min-h-[590px] items-end gap-10 py-12 sm:py-16 lg:grid-cols-[1.1fr_.9fr] lg:py-20">
        <div className="max-w-2xl"><p className="eyebrow mb-6">01 / TRAINING, WITHOUT THE RUNAROUND</p><h1 className="font-display text-[clamp(3.5rem,12vw,7.8rem)] font-extrabold leading-[0.83] tracking-[-0.09em]">LEARN<br />TO <span className="text-[#3d6854]">DRIVE.</span><br />YOUR WAY.</h1><p className="mt-8 max-w-lg text-base leading-7 text-black/65">Find a verified local driving instructor. Compare transparent packages. Book a real slot and meet at a point that works for you.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/learn" className="btn-primary">Find an instructor <ArrowDownRight className="h-4 w-4" /></Link><Link href="/teach" className="btn-quiet">Teach with drivenow <ArrowUpRight className="h-4 w-4" /></Link></div><div className="mt-10 flex flex-wrap gap-x-5 gap-y-2 text-[10px] font-bold tracking-[0.12em] text-black/55"><span>VERIFIED PROFILES</span><span className="hidden sm:block">/</span><span>TRANSPARENT PRICES</span><span className="hidden sm:block">/</span><span>SECURE CHECKOUT</span></div></div>
        <div className="relative mx-auto w-full max-w-md self-center lg:self-end"><div className="absolute -inset-4 border border-black/15" /><div className="relative overflow-hidden border-2 border-[#141414] bg-[#141414] p-4 text-[#f5f5f2]"><div className="flex items-center justify-between border-b border-white/20 pb-3 text-[10px] font-bold tracking-[0.16em]"><span>DRIVENOW / LOCAL MATCH</span><span className="text-[#a6d4b0]">ACTIVE</span></div><div className="relative mt-4 aspect-[4/5] overflow-hidden border border-white/20 bg-[#202221]"><div className="absolute inset-0 opacity-35 [background-image:linear-gradient(#ffffff1a_1px,transparent_1px),linear-gradient(90deg,#ffffff1a_1px,transparent_1px)] [background-size:32px_32px]" /><div className="route-arc absolute left-[12%] top-[20%] h-[54%] w-[74%] rounded-[50%] border-2 border-dashed border-[#a6d4b0]" /><span className="map-node left-[19%] top-[28%]">YOU</span><span className="map-node right-[15%] top-[63%]">OPEN</span><span className="map-node bottom-[17%] left-[43%]">AREA</span><div className="absolute bottom-4 left-4 right-4 border border-white/20 bg-[#141414]/95 p-4"><p className="text-[10px] font-bold tracking-[0.16em] text-white/55">DISCOVER WHEN READY</p><p className="mt-2 font-display text-2xl font-bold tracking-[-0.06em]">A better route to your first lesson.</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-[9px] font-bold tracking-[0.12em] text-white/55"><span>LOCATION</span><span>AVAILABILITY</span><span>TRUST</span></div></div></div>
      </div></section>
      <section className="border-b border-black/15 bg-[#141414] text-white"><div className="container grid gap-px bg-white/15 lg:grid-cols-3">{pillars.map(({ no, title, body, icon: Icon }) => <article key={no} className="bg-[#141414] p-7 sm:p-9"><div className="flex items-center justify-between text-[10px] font-bold tracking-[0.16em] text-white/50"><span>{no}</span><Icon className="h-4 w-4 text-[#a6d4b0]" /></div><h2 className="mt-14 font-display text-4xl font-extrabold tracking-[-0.07em]">{title}</h2><p className="mt-4 max-w-sm text-sm leading-6 text-white/65">{body}</p></article>)}</div></section>
      <section className="container grid gap-8 py-14 lg:grid-cols-[1fr_.75fr]"><div><p className="eyebrow">ONE APP / TWO WORKSPACES</p><h2 className="mt-4 max-w-xl font-display text-5xl font-extrabold leading-[0.9] tracking-[-0.075em]">BUILT FOR THE LEARNER. <span className="text-black/35">READY FOR THE INSTRUCTOR.</span></h2></div><div className="border-t-2 border-black pt-5 text-sm leading-7 text-black/65"><p>drivenow keeps the full journey in one secure product: a learner books a confirmed lesson, while an instructor manages verification, availability, active jobs and earnings.</p><Link href="/admin" className="mt-5 inline-flex items-center gap-2 text-xs font-bold tracking-[0.1em] underline underline-offset-4">ADMIN VERIFICATION <ArrowUpRight className="h-3.5 w-3.5" /></Link></div></section>
      <section className="border-t border-black/15 py-5"><div className="container flex flex-wrap items-center justify-between gap-3 text-[10px] font-bold tracking-[0.16em] text-black/50"><span>DRIVENOW / V1 MARKETPLACE</span><span>LEARN · TEACH · VERIFY</span></div></section>
    </main>
  </div>;
}
