import { useAuth } from "@/_core/hooks/useAuth";
import { AccessDenied, WorkspaceHeader } from "@/components/DrivenowShell";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, BadgeIndianRupee, CheckCircle2, Clock3, Loader2, PauseCircle } from "lucide-react";
import { Link } from "wouter";

const currency = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const inr = (paise: number) => currency.format(paise / 100);

export default function PayoutLedger() {
  const { isAuthenticated, loading } = useAuth();
  const { data, isLoading } = trpc.marketplace.teach.earnings.useQuery(undefined, { enabled: isAuthenticated });
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#141414] text-[10px] font-bold tracking-[0.18em] text-white/55">LOADING PAYOUTS</div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#e5e6e3]"><AccessDenied title="Sign in to view earnings" /></div>;
  return <WorkspaceHeader mode="TEACH" title="Payout ledger"><Link href="/teach" className="mt-6 inline-flex items-center gap-2 text-[10px] font-bold tracking-[0.14em] text-white/55"><ArrowLeft className="h-3.5 w-3.5" /> JOBS</Link>{isLoading || !data ? <p className="mt-8 text-sm text-white/50">Loading settlement records…</p> : <><section className="mt-6 grid gap-px border border-white/20 bg-white/15 sm:grid-cols-3"><div className="bg-[#141414] p-5"><p className="eyebrow text-white/45">ELIGIBLE EARNINGS</p><p className="mt-3 font-display text-3xl font-bold tracking-[-0.07em]">{inr(data.netPaise)}</p></div><div className="bg-[#141414] p-5"><p className="eyebrow text-white/45">COMPLETED LESSONS</p><p className="mt-3 font-display text-3xl font-bold tracking-[-0.07em]">{data.completed.length}</p></div><div className="bg-[#a6d4b0] p-5 text-[#141414]"><p className="text-[10px] font-extrabold tracking-[0.17em] text-[#23412f]">SETTLEMENT STATUS</p><p className="mt-3 font-display text-2xl font-bold tracking-[-0.07em]">TRACKED</p></div></section><section className="mt-5 border border-white/20 bg-white/[.04] p-5"><p className="eyebrow text-white/45">COMPLETED LESSONS</p>{data.completed.length === 0 ? <p className="mt-4 border border-dashed border-white/20 p-5 text-sm text-white/50">Completed, paid lessons will appear here as payout-eligible records.</p> : <div className="mt-4 space-y-2">{data.completed.map(booking => { const paid = booking.payoutStatus === "paid"; const held = booking.payoutStatus === "held"; return <article key={booking.id} className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 py-4"><div><p className="font-display text-lg font-bold tracking-[-0.04em]">{booking.packageName}</p><p className="mt-1 text-xs text-white/50">Completed {new Date(booking.scheduledStart).toLocaleDateString("en-IN", { dateStyle: "medium" })}</p></div><div className="flex items-center gap-4"><span className="text-sm font-bold">{inr(booking.pricePaise - booking.platformFeePaise)}</span><span className={paid ? "inline-flex items-center gap-1 border border-[#a6d4b0]/40 bg-[#a6d4b0]/15 px-2 py-1 text-[9px] font-bold tracking-[0.1em] text-[#a6d4b0]" : held ? "inline-flex items-center gap-1 border border-amber-300/40 bg-amber-100/10 px-2 py-1 text-[9px] font-bold tracking-[0.1em] text-amber-200" : "inline-flex items-center gap-1 border border-white/20 px-2 py-1 text-[9px] font-bold tracking-[0.1em] text-white/65"}>{paid ? <CheckCircle2 className="h-3 w-3" /> : held ? <PauseCircle className="h-3 w-3" /> : <Clock3 className="h-3 w-3" />}{booking.payoutStatus.replaceAll("_", " ")}</span></div></article>; })}</div>}</section></>}</WorkspaceHeader>;
}
