import { useAuth } from "@/_core/hooks/useAuth";
import { AccessDenied, LearnerShell } from "@/components/DrivenowShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Bell, CarFront, GraduationCap, Loader2, LogOut, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";

export default function Profile() {
  const { user, isAuthenticated, loading, logout } = useAuth();
  const { data: profile, isLoading } = trpc.marketplace.profile.me.useQuery(undefined, { enabled: isAuthenticated });
  const { data: notifications = [] } = trpc.marketplace.profile.notifications.useQuery(undefined, { enabled: isAuthenticated });
  const switchRole = trpc.marketplace.profile.switchRole.useMutation();
  const [, navigate] = useLocation();
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#e5e6e3] text-[10px] font-bold tracking-[0.18em]">LOADING PROFILE</div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#e5e6e3]"><AccessDenied title="Sign in to see your profile" /></div>;
  return <LearnerShell title="Account"><section className="border-2 border-black bg-[#f5f5f2] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">SECURE ACCOUNT</p><h2 className="mt-2 font-display text-3xl font-extrabold tracking-[-0.07em]">{profile?.fullName || user?.name || "drivenow member"}</h2><p className="mt-2 text-sm text-black/60">{user?.email || "Your account is authenticated by drivenow."}</p></div><span className="inline-flex items-center gap-1 border border-[#3d6854]/30 bg-[#d8e6d9] px-2 py-1 text-[9px] font-bold text-[#23412f]"><ShieldCheck className="h-3 w-3" /> SECURE SESSION</span></div><div className="mt-6 grid gap-3 border-t border-black/15 pt-5 sm:grid-cols-2"><button onClick={() => { if (profile?.activeRole === "learner") return navigate("/learn"); switchRole.mutate({ role: "learner" }, { onSuccess: () => navigate("/learn") }); }} className="group flex min-h-28 flex-col justify-between border border-black/15 bg-white p-4 text-left hover:border-black"><GraduationCap className="h-5 w-5" /><span><strong className="block font-display text-xl tracking-[-0.05em]">LEARN</strong><span className="text-xs text-black/55">Discover and manage lessons</span></span></button><button onClick={() => { if (profile?.activeRole === "instructor") return navigate("/teach"); switchRole.mutate({ role: "instructor" }, { onSuccess: () => navigate("/teach"), onError: () => navigate("/teach/onboarding") }); }} className="group flex min-h-28 flex-col justify-between border border-black/15 bg-[#141414] p-4 text-left text-white hover:border-[#a6d4b0]"><CarFront className="h-5 w-5 text-[#a6d4b0]" /><span><strong className="block font-display text-xl tracking-[-0.05em]">TEACH</strong><span className="text-xs text-white/55">Verification and jobs workspace</span></span></button></div><Button variant="outline" className="mt-5 border-black/20 text-xs font-bold" onClick={() => logout() }><LogOut className="mr-2 h-4 w-4" />Sign out</Button></section><section className="mt-5 border border-black/15 bg-[#f5f5f2] p-5"><div className="flex items-center justify-between"><div><p className="eyebrow">NOTIFICATIONS</p><h2 className="mt-1 font-display text-2xl font-bold tracking-[-0.06em]">ROUTE UPDATES</h2></div><Bell className="h-5 w-5" /></div>{notifications.length === 0 ? <p className="mt-5 border border-dashed border-black/20 p-4 text-sm text-black/55">Booking, verification, cancellation, and lesson updates will appear here.</p> : <div className="mt-5 space-y-3">{notifications.map(item => <article key={item.id} className="border-t border-black/10 pt-3"><p className="text-sm font-bold">{item.title}</p><p className="mt-1 text-xs leading-5 text-black/60">{item.body}</p></article>)}</div>}</section></LearnerShell>;
}
