import { ArrowRight, CarFront, GraduationCap, ShieldCheck } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { AccessDenied, AppHeader } from "@/components/DrivenowShell";
import { startLogin } from "@/const";
import { Link } from "wouter";

export default function Start() {
  const { isAuthenticated, user, loading } = useAuth();
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#e5e6e3] text-xs font-bold tracking-[0.18em]">LOADING SECURE SESSION</div>;
  if (!isAuthenticated) return <div className="min-h-screen bg-[#e5e6e3]"><AppHeader eyebrow="SECURE ACCESS" /><AccessDenied title="ONE ACCOUNT. TWO ROUTES." description="Sign in once to set up learning, teaching, or both workspaces." /></div>;
  return <div className="min-h-screen bg-[#e5e6e3]"><AppHeader eyebrow="CHOOSE YOUR ROUTE" /><main className="container py-10 sm:py-16"><p className="eyebrow">WELCOME {user?.name?.toUpperCase() || "BACK"}</p><h1 className="mt-3 max-w-lg font-display text-5xl font-extrabold leading-[0.88] tracking-[-0.08em]">HOW WILL YOU USE EAZYSERVX?</h1><div className="mt-10 grid gap-4 lg:grid-cols-2"><Link href="/learn/onboarding" className="group border-2 border-black bg-[#f5f5f2] p-6 transition hover:-translate-y-1 hover:bg-[#d8e6d9]"><GraduationCap className="h-6 w-6" /><p className="mt-12 text-[10px] font-bold tracking-[0.16em] text-black/55">LEARNER</p><h2 className="mt-2 font-display text-4xl font-extrabold tracking-[-0.07em]">FIND A CERTIFIED INSTRUCTOR.</h2><p className="mt-4 max-w-md text-sm leading-6 text-black/60">Set your training area, compare options and book the first lesson.</p><span className="mt-8 inline-flex items-center gap-2 text-xs font-bold tracking-[0.12em]">START LEARNING <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link><Link href="/teach/onboarding" className="group border-2 border-black bg-[#141414] p-6 text-white transition hover:-translate-y-1"><CarFront className="h-6 w-6 text-[#a6d4b0]" /><p className="mt-12 text-[10px] font-bold tracking-[0.16em] text-white/55">INSTRUCTOR</p><h2 className="mt-2 font-display text-4xl font-extrabold tracking-[-0.07em]">BUILD A LOCAL TEACHING ROUTE.</h2><p className="mt-4 max-w-md text-sm leading-6 text-white/65">Apply, get verified, set availability and receive nearby student requests.</p><span className="mt-8 inline-flex items-center gap-2 text-xs font-bold tracking-[0.12em]">APPLY TO TEACH <ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></span></Link></div><div className="mt-8 flex items-center gap-3 border-t border-black/15 pt-5 text-xs text-black/55"><ShieldCheck className="h-4 w-4" /> Your workspaces stay under the same secure EazyservX account.</div></main></div>;
}
